version: "3.9"

services:
    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        networks:
            - laravel_network
        ports:
            - "8081:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql

    php:
        build:
            context: ./.docker/php
        container_name: laravel_php
        networks:
            - laravel_network
        volumes:
            - ./:/var/www
        environment:
            - PHP_FPM_CLEAR_ENV=no

    mysql:
        image: mysql:latest
        container_name: laravel_mysql
        networks:
            - laravel_network
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=password

    node:
        image: node:latest
        container_name: laravel_node
        networks:
            - laravel_network
        volumes:
            - ./:/var/www
        working_dir: /var/www
        command: sh -c "npm install && npm run build"

volumes:
    mysql_data:
networks:
    laravel_network:
